global:
  scrape_interval:     5s
  evaluation_interval: 5s
scrape_configs:
  - job_name: 'rabbitmq-without'
    static_configs:
      - targets: ['rabbitmq:15692']
  - job_name: 'rabbitmq-with-amqproxy'
    static_configs:
      - targets: ['rabbitmq2:15692']